### PR TITLE
Context menu to highlight text and spot it

### LINKED ISSUE #6: Feature: Allow users to highlight any text from browser in order to find a corresponding song on Spotify
Use-Case:

- Highlight certain text on the browser
- Right click on highlighted text
- Select  'SPOTTED! Search on Spotify'
- SPOT opens, auto-searchs for highlighted text
- Displays Results

### PR DESCRIPTION
**Pull request by schezfaz**
Fixes #6 

- Store highlighted text  when SPOT context menu is selected -->in local storage
- Retrieve strored highlighted text and query it to find top 3 related songs on spotify
- Notify using chrome notifications to indicate that search results are ready
- reset local storagevalue  to  null

### CODE REVIEW

**Comment by schezfaz** [comment]
Hey @saiflakhani, let me know what you think!

**Comment by schezfaz** [comment]
@saiflakhani I think I'm gonna go ahead and merge it, for now! Let me know your thoughts regardless hehe

**Comment by saiflakhani** [comment]
Hey! This is great!
Sorry I've been really busy this past week. 

The notification doesn't seem to pop up for me though. Is there something I'm missing?

**Comment by schezfaz** [comment]
@saiflakhani haha no problem! Are you able to view the notifications? If not, I believe there is some configuration/permissions required within your browser settings. 

And, yes!! Will push the code for the add functionality in a bit. Post which, all that will remain is some thorough testing :P

**Pull request merged**
