### PR TITLE
Add config file for credentials

### PR DESCRIPTION
**Pull request by saiflakhani**
- Now all credentials will be safely stored inside a file "config.js"
- It is untracked by git, so any pulls will not change its contents
- Added a file called ```config_sample.js``` for ease of first-time installation
- Updated README to reflect changes.

### CODE REVIEW

**Comment by schezfaz** [comment]
Hi @saiflakhani 

Need to escape the forward slashes while creating the REDIRECT_URI dynamically using the EXTENSION_ID from config.js!

`const REDIRECT_URI = encodeURIComponent('https://' + EXTENSION_ID + '.chromiumapp.org/');
`  

-reverted the PR for now, will circle back to this later




image

**Comment by schezfaz** [comment]
Apologies for the delay once again!

**Comment by saiflakhani** [comment]
I didn't quite understand. What went wrong?

**Comment by schezfaz** [comment]
So basically, the REDIRECT_URI was not able to escapse the forward slashes (as depicted in the screenshot after console.logging it), because of which  the redirect url value was set to undefined. So whenever someone clicked on 'sign-in & authorise'  the pop-up would not open, which is which the extension was stuck at the same landing pop-up page only.

What i did was:
- Created a config.js file 
- Added the required variable values: Extension and Client ID

Let me know if I may have missed something! is it working on your local?

**Comment by saiflakhani** [comment]
Hmm. It was working on local, but I'll get back to you on this.

**Pull request merged**
